"""Simple decision engine placeholder."""

from typing import Dict, Any


def generate_recommendation(coin: str, profile: str, explain: bool, user: Any) -> Dict[str, Any]:
    """Return a dummy recommendation for the given coin."""
    recommendation = {
        "coin": coin,
        "profile": profile,
        "signal": "buy",
    }
    if explain:
        recommendation["explanation"] = "Generated by placeholder engine"
    return recommendation

